[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  external_node_modules = ["express", "mongoose", "cors", "cookie-parser", "dotenv", "jsonwebtoken", "bcrypt-nodejs"]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888